### ISSUE TITLE
新增资产提示权限校验未通过

### ISSUE THREAD

**Issue by dearliuliu0522** [ztkuaikuai/MiaoJi#15]
连接云端函数或本地函数都会出现这个问题。如下图：
![image](https://github.com/ztkuaikuai/MiaoJi/assets/95074196/a56d2b64-773d-48c7-8974-214a045d3539)
经查，是下图的add导致的：
![image](https://github.com/ztkuaikuai/MiaoJi/assets/95074196/268a5e9c-3446-49d5-b8e4-b6d302760ca2)
官网建议按照下图的方式排查：
![image](https://github.com/ztkuaikuai/MiaoJi/assets/95074196/17a330e6-abeb-4d6b-a695-506a88a170f8)
我的“mj-user-assets”表的permissions如下：
![image](https://github.com/ztkuaikuai/MiaoJi/assets/95074196/6f5d3fa2-8f47-4b40-8c02-e468de5baf2d)
请问是什么原因？

**Comment by ztkuaikuai** [comment]
可以看下你的uni-id-users的表吗，在添加资产，即create时，会判断role是否含有USER的角色，如果你的uni-id-users的role属性没有USER角色，那么会添加失败

**Comment by dearliuliu0522** [comment]
![image](https://github.com/ztkuaikuai/MiaoJi/assets/95074196/4585eeb8-1d6b-47f7-9de5-3f879d5d6d79)

没有发现role属性？我看表结构里是有role属性的。我实在微信小程序开发工具中用微信一键登录的。

**Comment by dearliuliu0522** [comment]
另外，uni_id_roles表是空的

**Comment by dearliuliu0522** [comment]
另外，uni-id-roles表是空的

**Comment by ztkuaikuai** [comment]
我明白了，你需要在用户注册时配置默认角色USER，需要在uni-id/config.json中进行配置，由于此文件涉及key，所以我gitiignore了。配置请参考：https://doc.dcloud.net.cn/uniCloud/uni-id/summary.html#config-defult-role

**Comment by ztkuaikuai** [comment]
uni-id-roles表是空的可以不用管，MiaoJi小程序没有用到此表，如果你需要给MiaoJi添加后台管理页面的话，则是需要role表的

**Comment by dearliuliu0522** [comment]
![image](https://github.com/ztkuaikuai/MiaoJi/assets/95074196/db5477ad-9c8e-4b25-a15b-11a887dca000)
按照你给的文档做了修改，重新上传后，还是不起作用。

**Comment by ztkuaikuai** [comment]
**大写**USER重新试试

**Comment by dearliuliu0522** [comment]
还是不行，下面是uni-id-users表数据：
![image](https://github.com/ztkuaikuai/MiaoJi/assets/95074196/6e285598-9ea6-46e7-ae21-a3487194f1fa)
下面是其表结构：
![image](https://github.com/ztkuaikuai/MiaoJi/assets/95074196/3dd78b45-e2fd-4ee3-b902-1bf43876f397)
![image](https://github.com/ztkuaikuai/MiaoJi/assets/95074196/9cd2b649-ca2a-4809-add2-169ccb81ac8d)
所有模块的config.json已经是下图中的值了：
![image](https://github.com/ztkuaikuai/MiaoJi/assets/95074196/996ddba1-b7d0-4415-8890-103b42bad331)

**Comment by ztkuaikuai** [comment]
尝试把你的uni-id-users中该用户删除，重新创建一个试试

**Comment by dearliuliu0522** [comment]
对的，通过删除数据库再重新上传，解决了。谢谢哈

**Comment by ztkuaikuai** [comment]
好的没事，有问题欢迎提issue😊
