### ISSUE TITLE
手机验证码登录时无法跳转到输入图形码界面

### ISSUE THREAD

**Issue by dearliuliu0522** [ztkuaikuai/MiaoJi#16]
如题。
![image](https://github.com/ztkuaikuai/MiaoJi/assets/95074196/2c69f264-3f07-4ca5-8be8-9da4dff5eb0e)

定位到的代码如下：
![image](https://github.com/ztkuaikuai/MiaoJi/assets/95074196/f6e93801-54c0-41ad-b27a-c28a9b352943)

login-smscode.vue文件是存在的：
![image](https://github.com/ztkuaikuai/MiaoJi/assets/95074196/9090e280-0be5-4dee-b773-765c6b985c78)

**Comment by ztkuaikuai** [comment]
有一部分原因是login-smscode.vue文件未在pages.json中注册导致的，另外妙计只做了微信一键登录功能，手机验证码登录可以参考文档：https://doc.dcloud.net.cn/uniCloud/uni-id/app.html

**Comment by dearliuliu0522** [comment]
懂了，谢谢！在一点点的学习代码。

**Comment by ztkuaikuai** [comment]
嗯嗯加油！
