### ISSUE TITLE
登录问题

### ISSUE THREAD

**Issue by PRINCE-10086** [ztkuaikuai/MiaoJi#22]
想问一下账号注销之后没法重新注册吗，只有一键登录功能，注销账号后，再点击微信登录就不能注册了

**Comment by ztkuaikuai** [comment]
这块没考虑全面，是个bug。目前注销账号就不能在注册登陆了，我目前把注销的账号改为了正常使用，你看看能登录上吗

**Comment by ztkuaikuai** [comment]
之后我会把注销这个功能删除掉，目前来说这个功能没有意义😇
